backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'CMS: Create {{collection}} "{{slug}}".'
    update: 'CMS: Update {{collection}} "{{slug}}".'
    delete: 'CMS: Delete {{collection}} "{{slug}}".'
    uploadMedia: 'CMS: Upload "{{path}}".'
    deleteMedia: 'CMS: Delete "{{path}}".'

media_folder: 'static/assets'
public_folder: 'assets'

publish_mode: editorial_workflow

collections:
  - label: 'Projects'
    name: 'projects'
    create: true
    folder: '_data/projects'
    label_singular: 'Project'
    preview_path: 'projects/{{slug}}'
    fields:
      - { label: 'Project Date', name: 'date', widget: 'date' }
      - { label: 'Title', name: 'title' }
      - { label: 'Cover Image', name: 'coverImage', widget: 'image' }
      - {
          label: 'Website Address',
          name: 'website',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Technology Tags',
          name: 'technologyTags',
          collection: 'technologies',
          multiple: true,
          searchFields: ['title'],
          valueField: 'title',
          widget: 'relation',
        }
      - { label: 'Summary', name: summary', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Technologies'
    name: 'technologies'
    create: true
    editor:
      preview: false
    extension: 'yml'
    folder: '_data/technologies'
    fields:
      - { label: 'Title', name: 'title' }
      - {
          label: 'Icon Image',
          name: 'iconImage',
          widget: 'image',
          allow_multiple: false,
        }
