backend:
  name: git-gateway
  branch: master

media_folder: 'static/assets'
public_folder: 'assets'

publish_mode: editorial_workflow

collections:
  - label: 'Projects'
    name: 'projects'
    label_singular: 'Project'
    folder: '_projects'
    create: true
    fields:
      - { label: 'Project Date', name: 'date', widget: 'date' }
      - { label: 'Title', name: 'title' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    preview_path: 'projects/{{slug}}'
